Add git contributros page to the application
ajaynegi45/Uttarakhand-Culture-NewUI pull request #206
Opened 2024-10-26 04:19 UTC by shubhagarwal1

#198 
<img width="1381" alt="Screenshot 2024-10-26 at 9 48 56 AM" src="https://github.com/user-attachments/assets/b32cb178-e48a-466c-a065-18e108d1e51e">

2024-10-26 07:19 UTC, ajaynegi45 requested changes
Hi @ ,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Improve UI more
- Add more Things

Once again, thank you for your contribution! ❤️

2024-10-26 07:19 UTC, closed without merging

2024-11-01 00:33 UTC, shubhagarwal1 commented on src/app/contributors/page.tsx
> +import { Loader2 } from "lucide-react";
hey can i work on thi s?

2024-11-01 03:16 UTC, ajaynegi45 commented on src/app/contributors/page.tsx
> +import { Loader2 } from "lucide-react";
> hey can i work on thi s?

Yes

2024-11-01 04:59 UTC, shubhagarwal1 commented on src/app/contributors/page.tsx
> +import { Loader2 } from "lucide-react";
please suggest meif any changes are required